// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyixojuekydwzllkwkkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aXhvanVla3lkd3psbGt3a2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODU1MTcsImV4cCI6MjA1NzI2MTUxN30.lmSu9LoMyGPDxqNlhOEERKLiZ9-COG_u2ZVAhbgr9ZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);